[package]
name = "webview-preact"
version = "0.1.0"
authors = ["paranoidcake <victorpanayotov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = { version = "0.5.4" }
wasm-bindgen = "0.2.63"
types = { path = "./types" }

serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
tokio = { version = "0.2", features = ["full"] }
pleco = "0.5.0"
